name: Update GitHub Profile README

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (you can adjust this)
  push:
    branches:
      - main  # Runs on any push to the 'main' branch

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This action checks out your code

      - name: Set up jq
        run: sudo apt-get install jq  # Install 'jq', a tool used for processing JSON

      - name: Fetch recent repositories
        run: |
          curl -s https://api.github.com/users/pavanputta14/repos?sort=updated&per_page=5 | jq -r '.[] | "* [\(.name)](https://github.com/pavanputta14/\(.name)) - \(.description)"' > projects.txt
          # Fetches the latest 5 repositories from your GitHub and formats them into a markdown list

      - name: Update README with latest projects
        run: |
          PROJECTS=$(cat projects.txt)  # Read the list of repositories into a variable
          sed -i "s|<!-- Recent Projects will be listed here dynamically -->|$PROJECTS|" README.md
          # Replaces the placeholder in your README with the actual list of recent projects

      - name: Commit changes
        run: |
          git add README.md  # Adds the updated README.md to Git
          git commit -m "Updated README with latest projects"  # Commits the changes
          git push  # Pushes the changes back to GitHub
